INSERT INTO joke (category_id, content) VALUES (3, 'Zašto je Chuck Norris najjači? Zato što vježba dva dana dnevno.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pričaju dvije gimnazijalke: Nema mi roditelja doma ovaj vikend! Bože, pa koja si ti sretnica! Možeš učiti naglas!');
INSERT INTO joke (category_id, content) VALUES (2, 'Došao Mujo u pizzeriju i naručio pizzu. Konobar ga upita: Želite da vam izrežem pizzu na 6 ili 12 komada? Ma na 6 komada, nema šanse da pojedem 12.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pita nastavnica hrvatskog jezika mladog osnovnoškolca: Reci ti meni što su to prilozi? Prilozi su: ketchup, majoneza, luk, salata...');
INSERT INTO joke (category_id, content) VALUES (3, 'Zašto je Chuck Norris najjači? Zato što vježba dva dana dnevno.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pričaju dvije gimnazijalke: Nema mi roditelja doma ovaj vikend! Bože, pa koja si ti sretnica! Možeš učiti naglas!');
INSERT INTO joke (category_id, content) VALUES (2, 'Došao Mujo u pizzeriju i naručio pizzu. Konobar ga upita: Želite da vam izrežem pizzu na 6 ili 12 komada? Ma na 6 komada, nema šanse da pojedem 12.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pita nastavnica hrvatskog jezika mladog osnovnoškolca: Reci ti meni što su to prilozi? Prilozi su: ketchup, majoneza, luk, salata...');
INSERT INTO joke (category_id, content) VALUES (3, 'Zašto je Chuck Norris najjači? Zato što vježba dva dana dnevno.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pričaju dvije gimnazijalke: Nema mi roditelja doma ovaj vikend! Bože, pa koja si ti sretnica! Možeš učiti naglas!');
INSERT INTO joke (category_id, content) VALUES (2, 'Došao Mujo u pizzeriju i naručio pizzu. Konobar ga upita: Želite da vam izrežem pizzu na 6 ili 12 komada? Ma na 6 komada, nema šanse da pojedem 12.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pita nastavnica hrvatskog jezika mladog osnovnoškolca: Reci ti meni što su to prilozi? Prilozi su: ketchup, majoneza, luk, salata...');
INSERT INTO joke (category_id, content) VALUES (3, 'Zašto je Chuck Norris najjači? Zato što vježba dva dana dnevno.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pričaju dvije gimnazijalke: Nema mi roditelja doma ovaj vikend! Bože, pa koja si ti sretnica! Možeš učiti naglas!');
INSERT INTO joke (category_id, content) VALUES (2, 'Došao Mujo u pizzeriju i naručio pizzu. Konobar ga upita: Želite da vam izrežem pizzu na 6 ili 12 komada? Ma na 6 komada, nema šanse da pojedem 12.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pita nastavnica hrvatskog jezika mladog osnovnoškolca: Reci ti meni što su to prilozi? Prilozi su: ketchup, majoneza, luk, salata...');
INSERT INTO joke (category_id, content) VALUES (3, 'Zašto je Chuck Norris najjači? Zato što vježba dva dana dnevno.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pričaju dvije gimnazijalke: Nema mi roditelja doma ovaj vikend! Bože, pa koja si ti sretnica! Možeš učiti naglas!');
INSERT INTO joke (category_id, content) VALUES (2, 'Došao Mujo u pizzeriju i naručio pizzu. Konobar ga upita: Želite da vam izrežem pizzu na 6 ili 12 komada? Ma na 6 komada, nema šanse da pojedem 12.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pita nastavnica hrvatskog jezika mladog osnovnoškolca: Reci ti meni što su to prilozi? Prilozi su: ketchup, majoneza, luk, salata...');
INSERT INTO joke (category_id, content) VALUES (3, 'Zašto je Chuck Norris najjači? Zato što vježba dva dana dnevno.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pričaju dvije gimnazijalke: Nema mi roditelja doma ovaj vikend! Bože, pa koja si ti sretnica! Možeš učiti naglas!');
INSERT INTO joke (category_id, content) VALUES (2, 'Došao Mujo u pizzeriju i naručio pizzu. Konobar ga upita: Želite da vam izrežem pizzu na 6 ili 12 komada? Ma na 6 komada, nema šanse da pojedem 12.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pita nastavnica hrvatskog jezika mladog osnovnoškolca: Reci ti meni što su to prilozi? Prilozi su: ketchup, majoneza, luk, salata...');
INSERT INTO joke (category_id, content) VALUES (3, 'Zašto je Chuck Norris najjači? Zato što vježba dva dana dnevno.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pričaju dvije gimnazijalke: Nema mi roditelja doma ovaj vikend! Bože, pa koja si ti sretnica! Možeš učiti naglas!');
INSERT INTO joke (category_id, content) VALUES (2, 'Došao Mujo u pizzeriju i naručio pizzu. Konobar ga upita: Želite da vam izrežem pizzu na 6 ili 12 komada? Ma na 6 komada, nema šanse da pojedem 12.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pita nastavnica hrvatskog jezika mladog osnovnoškolca: Reci ti meni što su to prilozi? Prilozi su: ketchup, majoneza, luk, salata...');
INSERT INTO joke (category_id, content) VALUES (3, 'Zašto je Chuck Norris najjači? Zato što vježba dva dana dnevno.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pričaju dvije gimnazijalke: Nema mi roditelja doma ovaj vikend! Bože, pa koja si ti sretnica! Možeš učiti naglas!');
INSERT INTO joke (category_id, content) VALUES (2, 'Došao Mujo u pizzeriju i naručio pizzu. Konobar ga upita: Želite da vam izrežem pizzu na 6 ili 12 komada? Ma na 6 komada, nema šanse da pojedem 12.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pita nastavnica hrvatskog jezika mladog osnovnoškolca: Reci ti meni što su to prilozi? Prilozi su: ketchup, majoneza, luk, salata...');
INSERT INTO joke (category_id, content) VALUES (3, 'Zašto je Chuck Norris najjači? Zato što vježba dva dana dnevno.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pričaju dvije gimnazijalke: Nema mi roditelja doma ovaj vikend! Bože, pa koja si ti sretnica! Možeš učiti naglas!');
INSERT INTO joke (category_id, content) VALUES (2, 'Došao Mujo u pizzeriju i naručio pizzu. Konobar ga upita: Želite da vam izrežem pizzu na 6 ili 12 komada? Ma na 6 komada, nema šanse da pojedem 12.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pita nastavnica hrvatskog jezika mladog osnovnoškolca: Reci ti meni što su to prilozi? Prilozi su: ketchup, majoneza, luk, salata...');
INSERT INTO joke (category_id, content) VALUES (3, 'Zašto je Chuck Norris najjači? Zato što vježba dva dana dnevno.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pričaju dvije gimnazijalke: Nema mi roditelja doma ovaj vikend! Bože, pa koja si ti sretnica! Možeš učiti naglas!');
INSERT INTO joke (category_id, content) VALUES (2, 'Došao Mujo u pizzeriju i naručio pizzu. Konobar ga upita: Želite da vam izrežem pizzu na 6 ili 12 komada? Ma na 6 komada, nema šanse da pojedem 12.');
INSERT INTO joke (category_id, content) VALUES (1, 'Pita nastavnica hrvatskog jezika mladog osnovnoškolca: Reci ti meni što su to prilozi? Prilozi su: ketchup, majoneza, luk, salata...');
